[package]
name = "browser"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3"
wasm-bindgen-futures = "0.4.24"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
wasm-logger = "0.2.0"
log = "0.4"

drogue-device = { path = "../../../device", features = ["log"], default-features = false }
embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false, features = ["executor-agnostic"] }
#embassy = {default-features = false, path = "../../../../../embassy/embassy", features = ["executor-agnostic"] }

critical-section = { version = "0.2.1", features = ["custom-impl"] }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
