[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "lora-discovery"
version = "0.1.0"

[workspace]

[dependencies]
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }
embedded-hal = { version = "0.2.4", features = ["unproven"] }
panic-probe = { version = "0.2.0", features = ["print-rtt"] }

drogue-device = { path = "../../../device", features = ["log", "chip+stm32l0x2", "lora+sx127x"], default-features = false }
cortex-m-rt = "0.6"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }

# TODO: Get rid of these embassy deps some day
# embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false}
# embassy-stm32 = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false}

embassy = {path = "../../../../../embassy/embassy", default-features = false}
embassy-stm32 = {path = "../../../../../embassy/embassy-stm32", default-features = false, features = ["stm32l072cz", "_gpio_v2", "_timer", "log", "pac"] }
stm32l0xx-hal = { version = "0.7.0", features = ["stm32l0x2"] }

[profile.release]
debug = 1
opt-level = "z"
lto = true

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
