[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-esp8266"
version = "0.1.0"

[workspace]

[dependencies]
panic-probe = { version = "0.2.0", features = ["print-rtt"] }
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }
rand_core = { version = "0.6.2", default-features = false }

drogue-device = { path = "../../../device", features = ["wifi+esp8266", "tls"], default-features = false }
drogue-tls = {git = "https://github.com/drogue-iot/drogue-tls.git", branch = "main", default-features = false}
# drogue-tls = {path = "../../../../drogue-tls", default-features = false, features = ["log"]}
wifi-app = { path = "../../common/wifi" }
cortex-m-rt = "0.6"
cortex-m = { version = "0.6", features = ["inline-asm"] }

embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false}
embassy-nrf = {git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false, features = ["nrf52833"]}
nrf52833-pac = { version = "0.9", features = ["rt"] }
#embassy = {path = "../../../../../embassy/embassy", default-features = false}
#embassy-nrf = {path = "../../../../../embassy/embassy-nrf", default-features = false, features = ["nrf52833"]}

heapless = "0.6"

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false