[package]
authors = ["Ulf Lilleengen <ulf.lilleengen@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "microbit-esp8266"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.4"
cortex-m-rt = { version = "0.6.11", features = ["device"] }
rtt-target = {version = "0.2.0", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1.1", features = ["cortex-m"] }
log = "0.4.11"
rtt-logger = "0.1.0"
drogue-device = { path = "../../../rt", features = ["chip+nrf52833", "wifi+esp8266" ]}
heapless = "0.5"

[dependencies.nrf52833-hal]
git = "https://github.com/lulf/nrf-hal.git"
branch = "uarte-embedded-serial"
features = ["rt"]

[[bin]]
name = "microbit-esp8266"
test = false
bench = false

[profile.release]
debug = true
opt-level = "z"
lto = true
