[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
drogue-device-macros = { path = "../macros" }

# embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false }
# embassy-nrf = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true }
# embassy-stm32 = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true }
# embassy-rp = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true }
# embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false, optional = true }

embassy = {default-features = false, path = "../../../embassy/embassy" }
embassy-nrf = {default-features = false, optional = true, path = "../../../embassy/embassy-nrf" }
embassy-stm32 = {default-features = false, optional = true, path = "../../../embassy/embassy-stm32" }
embassy-rp = {default-features = false, optional = true, path = "../../../embassy/embassy-rp" }
embassy-std = {default-features = false, optional = true, path = "../../../embassy/embassy-std" }

# LoRa dependencies
lorawan-device = { git = "https://github.com/lulf/rust-lorawan.git", rev = "2279fe55e9aeda5d3b9d2593763e3b2c031fa695", default-features = false, optional = true }
lorawan-encoding = { git = "https://github.com/lulf/rust-lorawan.git", rev = "2279fe55e9aeda5d3b9d2593763e3b2c031fa695", default-features = false, features = ["default-crypto"], optional = true }
bit_field = { version = "0.10", optional = true }

# Wifi Dependencies
nom = { version = "6.1.2", default-features = false, optional = true }
moveslice = { version = "2.0", optional = true }

# Utilities
futures = { version = "0.3", default-features = false }
heapless = "0.6"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
atomic-polyfill = "0.1"
generic-array = "0.14"
critical-section = "0.2.1"

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

[dev-dependencies]
# embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false }
embassy-std = {default-features = false, path = "../../../embassy/embassy-std" }
futures = { version = "0.3", default-features = false, features = ["executor"] }
arrayvec = { version = "0.6" }
env_logger = "0.8"

[features]
default = [ "log", "std" ]
std = ["embassy/std", "embassy-std" ]
"chip+rp" = [ "embassy-rp", "embassy-rp/defmt", "chip+nrf" ]
"chip+nrf52833" = ["embassy-nrf", "embassy-nrf/nrf52833", "chip+nrf"]
"chip+stm32l0x2" = ["embassy-stm32", "embassy-stm32/stm32l072cz", "chip+stm32" ]
"lora+sx127x" = ["lorawan-device", "lorawan-encoding", "bit_field", "log"]
"lora+rak811" = ["log", "nom", "moveslice"]
"wifi+esp8266" = ["log", "nom", "moveslice"]
lora = []
wifi = []
fonts = []
"chip+nrf" = []
"chip+stm32" = []

defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
