[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "hello"
version = "0.1.0"

[workspace]

[dependencies]
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std"] }
embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "master", features = ["std"] }
embassy-std = {git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false }

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
